site_name: QurioSkill Python Docs
site_url: https://qurioskill.github.io/
theme:
  name: material
nav:
  - Home: index.md
  - Concepts:
    - Variables: variables.md
    - Data Types: data-types.md
    - Functions: functions.md
  - Important Lists:
    - Common Functions: common-functions.md

