site_name: QurioSkill Python Docs
site_url: https://qurioskill.github.io/
theme:
  name: material
nav:
  - Home: index.md
  - How To Tackle Coding Tasks: how-to-tackle-coding-tasks.md
  - Concepts:
    - Variables: variables.md
    - Data Types:
        - Arithmitic: arithmitic.md
        - String: strings.md
        - List: list.md
        - Dictionary: dictionary.md
        - More: more_datatypes.md
    - Functions: functions.md
    - Conditionals: conditionals.md
    - Flow of Control: flow-of-control.md
    - While Loops: while-loops.md
    - Modules: modules.md
  - Important:
    - Common Functions: common-functions.md
    - Resources: resources.md

