site_name: QurioSkill Python Docs
site_url: https://qurioskill.github.io/
theme:
  name: material
nav:
  - Home: index.md
  - How To Tackle Coding Tasks: how-to-tackle-coding-tasks.md
  - Concepts:
    - Variables: variables.md
    - Data Types: data-types.md
    - Functions: functions.md
    - Conditionals: conditionals.md
    - Flow of Control: flow-of-control.md
    - While Loops: while-loops.md
  - Important Lists:
    - Common Functions: common-functions.md

